### PR TITLE
Update mpas-ocean version

### PR DESCRIPTION
**Pull request by dazlich**
The mpas-ocean component is updated to a new version: branch 'vanroekel/ocean/update-nonhydro-2-15-2023' of https://github.com/vanroekel/E3SM . This new version permits GPU acceleration to be implemented to the ocean, and features a non-hydrostatic treatment of the vertical coordinate in the split-implicit time integration scheme.

The changes in CMEPS involve adding entries for new wave to ocean coupling variables.

This is part of a package of PRs for branches named update/ocean:
EarthWorksOrg /mpas-ocean PR #14
EarthWorksOrg /mpas-seaice PR #16
EarthWorksOrg /mpas-framework PR #10
EarthWorksOrg /CMEPS PR #12
EarthWorksOrg/EarthWorks PR #47

To clone this version of Earthworks use the update/ocean branch.

### CODE REVIEW

**Comment by dazlich** [comment]
These associated PRs need to be updated
EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)
EarthWorksOrg /mpas-seaice PR [#17](https://github.com/EarthWorksOrg/mpas-seaice/pull/17)
EarthWorksOrg /mpas-framework PR [#10](https://github.com/EarthWorksOrg/mpas-framework/pull/10)
EarthWorksOrg /CMEPS PR [#12](https://github.com/EarthWorksOrg/CMEPS/pull/12)
EarthWorksOrg/EarthWorks PR [#75](https://github.com/EarthWorksOrg/EarthWorks/pull/75) (incorporates above)

**Comment by dazlich** [comment]
Also, I have merge issues to deal with with EarthWorksOrg /mpas-ocean PR ~~#15~~ [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)

**Comment by dazlich** [comment]
@gdicker1 - somehow the PRs I have linked to say ESCOMP, and it wants to push to the ew-main branch instead of the ew-develop branch. Can you help me fix this?

**Comment by dazlich** [comment]
@gdicker1 - Ok, I got the base changed, but the ESCOMP in the listed associated PRs has me stumped.

**Comment by gdicker1** [comment]
I also don't know why the numbering jumps to ESCOMP by default, but I've been seeing it in few places... I'll ask around to see if any one else knows why upstream PRs are being preferred.

**Comment by gdicker1** [comment]
@dazlich, from what I figured out, GitHub just works that way. The workaround would just be explicit links instead. If you don't mind, I can go through and get all the links fixed up.

**Comment by dazlich** [comment]
Appreciate it

On Oct 11, 2024, at 11:14 AM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@dazlich<https://github.com/dazlich>, from what I figured out, GitHub just works that way. The workaround would just be explicit links instead. If you don't mind, I can go through and get all the links fixed up.

**Review by gdicker1 — APPROVED** [review]

**Pull request merged**
