### PR TITLE
Update with 'cmeps0.14.2' tag

### PR DESCRIPTION
**Pull request by gdicker1**
Advance EarthWorksOrg/CMEPS to include changes from the ESCOMP/CMEPS 'cmeps0.14.2' tag. This matches with updates of other externals to what's used in ESCOMP/CESM tag 'cesm2_3_beta11'

### CODE REVIEW

**Comment by gdicker1** [comment]
The force push was to include [6c56358](https://github.com/EarthWorksOrg/CMEPS/pull/1/commits/6c5635838a0fd22a55a1bc41b02a7afb82a2deaf) which changes routines that @dazlich added to a new interface for addfld and addmap routines.

**Comment by gdicker1** [comment]
> The force push was to include [6c56358](https://github.com/EarthWorksOrg/CMEPS/pull/1/commits/6c5635838a0fd22a55a1bc41b02a7afb82a2deaf) which changes routines that @dazlich added to a new interface for addfld and addmap routines.

@dazlich, this is why I added you as a reviewer here. I tested that this builds with FullyCoupled compset, but if you would double check the work in this commit I'd appreciate it.

**Comment by dazlich** [comment]
Ok, will do @gdicker1. So, if I check out the develop branch of EarthWorks, what do I want the checkout of CMEPS in Externals.cfg to read to that I am testing this?

On May 3, 2023, at 12:15 PM, gdicker1 ***@***.***> wrote:


** Caution: EXTERNAL Sender **


The force push was to include 6c56358<https://github.com/EarthWorksOrg/CMEPS/pull/1/commits/6c5635838a0fd22a55a1bc41b02a7afb82a2deaf> which changes routines that @dazlich<https://github.com/dazlich> added to a new interface for addfld and addmap routines.

@dazlich<https://github.com/dazlich>, this is why I added you as a reviewer here. I tested that this builds with FullyCoupled compset, but if you would double check the work in this commit I'd appreciate it.

**Comment by gdicker1** [comment]
> Ok, will do @gdicker1. So, if I check out the develop branch of EarthWorks, what do I want the checkout of CMEPS in Externals.cfg to read to that I am testing this?

Since it is a CMEPS change it is a little difficult to test in isolation (cime, ccs_configs, and others need to play nicely together). Maybe this PR is best tested through https://github.com/EarthWorksOrg/EarthWorks/pull/12. 

To more directly answer the question, `git clone -b update/cesm2_3_beta11 https://github.com/EarthWorksOrg/EarthWorks` should get you what you need and after running `manage_externals` you should have CMEPS checked out with the `cmeps-ew1.0.001` tag.

**Pull request merged**
